### PR TITLE
Run update ranked statuses only if online

### PR DESCRIPTION
**Pull request by AiAe**

### CODE REVIEW

**Comment by Swan** [comment]
What's the reason for this PR? That endpoint doesn't require you to be online.

**Comment by IceDynamix** [comment]
Dev client will report an error on updating ranked statuses every time you leave the editor otherwise

**Comment by Swan** [comment]
> Dev client will report an error on updating ranked statuses every time you leave the editor otherwise

This is because there's no API server running locally? Not seeing any errors right now...

**Comment by AiAe** [comment]
> > Dev client will report an error on updating ranked statuses every time you leave the editor otherwise
> 
> This is because there's no API server running locally? Not seeing any errors right now...

https://github.com/Quaver/Quaver/issues/3694
This happens when Steam is running in offline. 
It wont resolve the issue exactly but will be one less thing

**Pull request merged**
