### PR TITLE
Playfield Tilt Config (Prototype)

### PR DESCRIPTION
**Pull request by staravia**
# What is this?
This new feature will allow players to play the game at a simulated perspective (similar to guitar hero and stepmania hallway/distant)

If you would like to check out a video, click here

## Config
A `PlayfieldTilt4K` and `PlayfieldTilt7K` Config value was created for this feature.

## Image Plane
To render the Playfield, I've created a 2d plane in the form of a trapezoid. The plane is a simple geometry that consists of 4096 quads. Because of how UV maps work, this much detail is needed. Illustration below:

## PreDraw()
A `PreDraw` method was also created in the Playfield and Ruleset abstracts due to xna wiping the renderer everytime we change Render Targets.

### CODE REVIEW

**Comment by YaLTeR** [comment]
> PreDraw

You're looking for `ScheduledRenderTargetDraws` or something like that. Was added recently for that exact purpose.

**Comment by YaLTeR** [comment]
> CreateOrthographicOffCenter

Wasn't orthographic, like, the opposite of perspective? Could that be the reason for the texture artifacts? Disclaimer: I don't know much about all this, but the texture artifacts seem extremely weird to me.

**Comment by staravia** [comment]
> 
> 
> > CreateOrthographicOffCenter
> 
> Wasn't orthographic, like, the opposite of perspective? Could that be the reason for the texture artifacts? Disclaimer: I don't know much about all this, but the texture artifacts seem extremely weird to me.

Yes that is true, but the entire game is in orthographic view. While we can create a perspective camera, everything will have to realign to the original playfield because we want to interpolate between how much it tilts and the default.

**Comment by YaLTeR** [comment]
Perspective transform is a matrix transform just like anything else. You should be able to render the playfield with a perspective transformation, and then render the rest in screen-space like it's done now.

**Comment by Swan** [comment]
Gonna close since there hasn't been progress on this for a while.

**Pull request closed without merging**
