### PR TITLE
[1.6.0] Add animation system for maps

### PR DESCRIPTION
**Pull request by WilliamQiufeng**
**Requires** https://github.com/Quaver/Quaver.API/pull/164 and https://github.com/Quaver/Wobble/pull/143

Allow using lua scripts to run an animation.

It currently has several ways of doing animations:
+ Segments and Triggers: A segment contains a function that is called repeatedly between a range of time. Triggers fire only once at a specific time.
   + A Tween Segment is added for smooth change in attributes of anything
   + An IntervalTrigger is used to fire a set number of times with a set interval
   + It supports dynamic adding and destroying, so you can use it with event triggers and other components
+ State Machines (Untested but added): A basic state machine that updates only the function of the current state. There can be multiple state machines at the same time.
+ Event trigger: You can set a lua callback for events like player hitting a note, or a new note entering the playfield.

Roadmap:
+ [x] Drawable Rotation
+ [x] Drawable scaling
  + [ ] Fix scaling orientation issue, observable with lane config preset
+ [x] Drawable inheritive tint and alpha
+ ~Game window manipulation~ Concluded as impossible
  + [ ] Letterboxing for wayland
+ [x] Shader support
+ [x] Layering system
+ [ ] Effect presets
  + [x] Lane swapping
  + [ ] Lane config (Changing the number of lanes e.g. 7K to 6K, etc.)
+ [x] Tweening scroll speed (#4210 )
+ [x] Beat-to-time converter (`beat(measure, beat` and `measure(measure)`)
+ [x] Audio sample loading and playing
+ [x] Script error count limiter
+ [x] Script update limiter
+ [x] Vectors
+ [x] Exec
+ [ ] Storage
+ [x] Fully index stage components
  + [x] LaneContainer(i) -> Lanes[i]
  + [x] UI
+ [ ] Design panel / Directive parsers

Check out https://github.com/WilliamQiufeng/QuaverAnimation for easy setup and example maps.

https://github.com/Quaver/Quaver/assets/32996262/83acbccb-c4fe-4117-95b1-6e837aaa92cb

https://github.com/Quaver/Quaver/assets/32996262/4836983b-39c0-4001-97c2-cc6d1a7e6720

https://github.com/Quaver/Quaver/assets/32996262/2da5705f-98d7-427d-8fd0-0b17d90484eb

https://github.com/Quaver/Quaver/assets/32996262/5b8aabd0-3b16-4730-b1ca-44cf68ce18cc

https://github.com/Quaver/Quaver/assets/32996262/2d6934c9-5bc4-469f-984d-e5b6d5b214f1

I'll add more previews some time. These are the ones I recorded several weeks ago.

### CODE REVIEW

**Comment by ESV-Sweetplum** [comment]
Any chance we'll be able to get fake notes?

**Comment by QiuFeng54321** [comment]
> Any chance we'll be able to get fake notes?

You can get a sprite of notes and playfield and put them there.

**Comment by EpiCreeper** [comment]
I was 100% sure it was just a mod, never realized this was actually coming eventually. We are just turning quaver into notitg now, huh?

**Comment by WilliamQiufeng** [comment]
A Lua-scripted storyboard was its intention, though it did extend to have some features in notITG inevitably. However, it is not aiming towards notITG as some of its features are, unfortunately,  too late or simply impossible to implement at this stage... It did start out as a fun little project I made to make me understand the code more, but it eventually became of interest to the community and the developers so I kept going for it.

**Comment by EpiCreeper** [comment]
i think creating levels under limitations can lead for more creative solutions. its ok that quaver wont have all of the notitg features (you can play nontitg for that experience), but wow, this could be so cool for sv mappers.

**Pull request closed without merging**
