### PR TITLE
Option to gray notes if hit early instead of despawning them

### PR DESCRIPTION
**Pull request by IceDynamix**
Addresses #2913 

Difference between old and new (dead color is barely visible because the tint in the default skin is low)
https://user-images.githubusercontent.com/22303902/112993502-9148e800-9169-11eb-9aa9-6d3e7d87c924.mp4

Only grays out notes hit outside of Marv-Great
https://user-images.githubusercontent.com/22303902/112993439-81c99f00-9169-11eb-8290-3c48a86f10cb.mp4

### CODE REVIEW

**Comment by andrewletz** [comment]
Good point about only graying out early hit notes that are below a certain threshold (i.e Good, Okay, & Miss). In my original issue I was incorrect in stating that it would be best to gray out all early hits. If you do hit a note early and get a Marv/Perf/Great, it should disappear instantly as that visual feedback is important (and expected). This also explains why osu!mania has some notes disappearing and others being grayed out when smashing early hits.

However, it seems osu!mania _only_ grays on early Misses, and will make the note disappear on any early judgement outside of a Miss. I personally think that what IceDynamix has implemented now is a better solution & a good default (gray out early hits below Great), but perhaps it should be made an individual toggle for each judgement so it is up to the user what notes they want to disappear. This would also accomplish what Jolomann requested above.

Something like this (current implementation default is bolded):
"Gray-out rather than disappear early Marvelous judgements" [**Off**/On]
"Gray-out rather than disappear Perfect judgements" [**Off**/On]
"Gray-out rather than disappear Great judgements" [**Off**/On]
"Gray-out rather than disappear Good judgements" [Off/**On**]
"Gray-out rather than disappear Okay judgements" [Off/**On**]
"Gray-out rather than disappear Miss judgements" [Off/**On**]

**Comment by IceDynamix** [comment]
I'll just make a dropdown, using 6 booleans isn't really necessary imo

**Comment by andrewletz** [comment]
Good point with the dropdown, no need to have granularity down to the specific judgement. 
I imagine it would read something like this:
"Gray-out rather than disappear all judgements below and including" [Marvelous/Perfect/Great/**Good**/Okay/Miss]

**Comment by Swan** [comment]
Closing since no progress has been made.

**Pull request closed without merging**
