### PR TITLE
Apply mods when toggling testplay

### LINKED ISSUE #3785: NSV mod stops applying to preview when autoplay is disabled
**Describe the bug**
When previewing a map with the NSV mod enabled, disabling autoplay results in SVs being applied to the preview. Seeking backwards results in incorrect scrolling behavior as well.

**To Reproduce**
1. Pick an SV map in song select.
2. Turn on NSV
3. Open map preview
4. Disable autoplay
5. Seek backwards

**Expected behavior**
A playable map preview with no SVs applied.

Video of bug:
https://cdn.discordapp.com/attachments/492960211271680030/1096930951088570480/2023-04-15_15-49-55.mp4

### PR DESCRIPTION
**Pull request by WilliamQiufeng**
Resolves #3785, #4201
uwu

### CODE REVIEW

**Review by Warp9000 — APPROVED** [review]

**Comment by AVY6** [comment]
this does not resolve my problem dude. i already applied the mods with toggling testplay. why wouldnt have i tried that before coming here?????? it just doesnt work. you clearly havent tested it for yourself because youd also be seeing the issue. i can see the map with NSV, but as soon as i try to playtest it with NSV, all the notes disappear and i cant practice.

**Comment by ESV-Sweetplum** [comment]
bro.... the changes are not live

**Comment by xzeph** [comment]
bro do you know how github works

**Comment by ESVEBE** [comment]
What map are you playing, because this does seem to be fixed on my end

https://github.com/user-attachments/assets/44bdf416-7d41-43e2-b2ad-dd6402566c80

**Comment by xzeph** [comment]
might ebe a canary thing

**Comment by ESVEBE** [comment]
It seems to be, you can enable the canary beta by going to quaver's properties in steam, and enabling the canary branch in betas

**Comment by Warp9000** [comment]
@AVY6 You can keep an eye on #updates in the discord server for when updates roll out.

**Comment by platonictf** [comment]
can we kill this person with a stone

**Pull request merged**
