### PR TITLE
Delete score button

### LINKED ISSUE #283: Deleting scores
**Is your feature request related to a problem? Please describe.**
Having scores you don't want to see (failed scores, worse scores etc)

**Describe the solution you'd like**
Being able to delete scores

### PR DESCRIPTION
**Pull request by nobbele**
Resolves #283

### CODE REVIEW

**Comment by YaLTeR** [comment]
Please attach a screenshot of how the button looks.

**Comment by nobbele** [comment]
bild

Some things will have to be move around. Should also probably be a proper sprite instead of a sprite text saying "X"

**Comment by YaLTeR** [comment]
Yeah, this looks kinda bad. I'll ask other team members if they've got design ideas.

**Comment by YaLTeR** [comment]
Swan says right click should be fixed first in Wobble and this should be bound to right click rather than a visible element. This PR will have to wait until I or someone else gets around to that. Thanks though!

**Pull request closed without merging**
