### PR TITLE
[1.5.0] Add proper support for hitsounds in plugins

### PR DESCRIPTION
**Pull request by Emik03**
- You cannot perform the `AddHitsound` or `RemoveHitsound` action type.
- It is impossible to get the underlying representation of `HitSounds` to perform arithmetic on.

This PR fixes both of those things.

### CODE REVIEW

**Comment by Emik03** [comment]
example plugin that needs this PR [qwe.zip](https://github.com/Quaver/Quaver/files/15275302/qwe.zip)

untested because i can't even reproduce the build for whatever reason

**Review by AiAe — CHANGES_REQUESTED** [review]
image

**Comment by AiAe** [comment]
With the latest plugin u've send in development i'm getting this error now
https://discord.com/channels/354206121386573824/570610717720313875/1262531603838533724
image

**Comment by Emik03** [comment]
Merged with #4105

**Pull request closed without merging**
