### PR TITLE
Linux support

### LINKED ISSUE #270: No success trying to build & run on Linux
I hit several issues trying to build and run Quaver on Linux, some of which I could fix, but not all of them. I am running Arch Linux x64 with dotnet 2.2.100.

I cloned the repository with submodules and proceeded with `dotnet restore`, which worked fine, except for three (possibly related) warnings:
```
/home/yalter/Source/cs/Quaver/Wobble/Wobble/Wobble.csproj : warning NU1701: Package 'MonoGame.Extended 1.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/home/yalter/Source/cs/Quaver/Quaver.sln]
/home/yalter/Source/cs/Quaver/Quaver/Quaver.csproj : warning NU1701: Package 'MonoGame.Extended 1.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/yalter/Source/cs/Quaver/Quaver.sln]
/home/yalter/Source/cs/Quaver/Quaver.Shared/Quaver.Shared.csproj : warning NU1701: Package 'MonoGame.Extended 1.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/yalter/Source/cs/Quaver/Quaver.sln]
```

Then I ran `dotnet msbuild /property:Configuration=Release` which also completed fine.

Finally, I tried to `dotnet bin/Release/netcoreapp2.1/Quaver.dll` to be hit with the first issue:
https://github.com/Quaver/Quaver/blob/c280702fce80456c7b9be68c0b870aa4fc5dbb34/Quaver/Program.cs#L24
This third `/` in the `file:///` pattern actually cuts off the first character of a Linux absolute path which makes it a relative path instead and breaks everything. Replacing the pattern with `file://` allowed me to progress through this step.

Next, `dotnet bin/Release/netcoreapp2.1/Quaver.dll` told me it couldn't load the Steam API and indeed, the repository seems to only contain the Windows `steam_api64.dll`. I went ahead and downloaded the Steamworks SDK, extracted `libsteam_api.so` out of there and placed it as `libsteam_api64.so` into the output directory along with `Quaver.dll`.

Now running the game seems to not produce any errors, but instead of actually launching the game it tries to download some unrelated 1 MB large game from Steam ("Spacewar"). I have no idea why or how to fix that. Downloading that from Steam and trying to run Quaver again makes it try running that "Spacewar" game.

### PR DESCRIPTION
**Pull request by YaLTeR**
Requires https://github.com/Quaver/Wobble/pull/16

Makes Quaver run on Linux, at least in Debug mode (can't test Release because no key).

Everything seems to work well, except the font rendering that's a little off, but that doesn't impact playability.

Resolves #270.

### CODE REVIEW

**Comment by YaLTeR** [comment]
That code for opening a folder in a file manager really asks to be abstracted into `Wobble.Platform`, but I'm not quite sure what the best class layout for that would be.

**Comment by Swan** [comment]
[Quaver/Wobble#16](https://github.com/Quaver/Wobble/pull/16) has been merged. Can you update the Wobble submodule to the latest master commit?

**Comment by Swan** [comment]
Also as far as opening a folder in the file manager goes - having it in a static class seems appropriate.

**Comment by YaLTeR** [comment]
Now depends on https://github.com/Quaver/Wobble/pull/17 for the abstraction. I'll update this to point at the correct submodule once it's merged.

**Comment by Swan** [comment]
Merged [Quaver/Wobble#17](https://github.com/Quaver/Wobble/pull/17). Please update the submodule, so I can merge this.

**Comment by YaLTeR** [comment]
Done.

**Pull request merged**
