### PR TITLE
Make Displaying Pausing Warning Toggleable

### PR DESCRIPTION
**Pull request by QiuFeng54321**
Some rages when seeing this notification, so I made it toggleable.

### CODE REVIEW

**Comment by YaLTeR** [comment]
Do we really need to take up space in the options menu with things like this? It's hard enough to find what you're looking for as is.

**Comment by QiuFeng54321** [comment]
> Do we really need to take up space in the options menu with things like this? It's hard enough to find what you're looking for as is.

Maybe we could put this option in Misc->Notification?

It does seem inappropriate to use an option item for just this, but I don't have any idea how else we could toggle it. Do you have any advise?

**Comment by YaLTeR** [comment]
Idk, could leave as ini-only, since the setting sounds quite specific.

**Comment by QiuFeng54321** [comment]
> Idk, could leave as ini-only, since the setting sounds quite specific.

OK, I removed the option item.

**Comment by Illuminati-CRAZ** [comment]
lgtm, I might add a similar setting for the quick exit setting to the pr

**Review by Illuminati-CRAZ — APPROVED** [review]

**Comment by AiAe** [comment]
I think we should avoid having "hidden" config settings, everything should be always available in-game.

**Comment by QiuFeng54321** [comment]
> I think we should avoid having "hidden" config settings, everything should be always available in-game.

I added an option item for it in `Options->Misc->Notifications`.

**Review by Warp9000 — APPROVED** [review]

**Pull request merged**
