### PR TITLE
Update everything to .NET 6.0 / .NET Standard 2.1

### PR DESCRIPTION
**Pull request by Swan**
@YaLTeR - Need you to test Linux
@AiAe - Need you to test Mac / find other ppl who are having issues to test

Build w/ .NET 6.0

### CODE REVIEW

**Comment by AiAe** [comment]
Tried to compile under MacOS and got this error:

```
Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/aiae/Dev/QuaverProjects/Quaver-swan/Quaver/bin/Debug/net6.0/Quaver.dll'. An attempt was made to load a program with an incorrect format.

File name: '/Users/aiae/Dev/QuaverProjects/Quaver-swan/Quaver/bin/Debug/net6.0/Quaver.dll'
```

**Comment by AiAe** [comment]
> Tried to compile under MacOS & run it and got this error:
> 
> ```
> Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/aiae/Dev/QuaverProjects/Quaver-swan/Quaver/bin/Debug/net6.0/Quaver.dll'. An attempt was made to load a program with an incorrect format.
> 
> File name: '/Users/aiae/Dev/QuaverProjects/Quaver-swan/Quaver/bin/Debug/net6.0/Quaver.dll'
> ```
> 
> Will try look more into it after work.

Fixed by removing the platform target from csproj to not be forced for x64, but now I will have to get all the 3rd party dlls we use for arm, to be able to build & run for it.

```[6:25:18] - RUNTIME - ERROR: System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Quaver.Shared.Online.SteamManager.Initialize()
   at Quaver.Program.Run() in /Users/aiae/Dev/QuaverProjects/Quaver-swan/Quaver/Program.cs:line 97
   at Quaver.Program.Main(String[] args) in /Users/aiae/Dev/QuaverProjects/Quaver-swan/Quaver/Program.cs:line 60
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Quaver.Shared.Online.SteamManager.Initialize()
   at Quaver.Program.Run() in /Users/aiae/Dev/QuaverProjects/Quaver-swan/Quaver/Program.cs:line 97
   at Quaver.Program.Main(String[] args) in /Users/aiae/Dev/QuaverProjects/Quaver-swan/Quaver/Program.cs:line 60
```

**Comment by Swan** [comment]
@AiAe How are you compiling it? Everything is working fine on mac with a fresh repo here.

**Comment by AiAe** [comment]
> @AiAe How are you compiling it? Everything is working fine on mac with a fresh repo here.

Do you use dotnet 6 for arm or the rosetta version, that might be the reason why. 
I have only the arm version.

**Pull request merged**
